# Generated by Django 4.2.5 on 2023-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="", upload_to="products/", verbose_name="Image"
            ),
            preserve_default=False,
        ),
    ]
