# Generated by Django 4.2.5 on 2023-09-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brand_category",
                to="products.category",
            ),
        ),
    ]
