# Generated by Django 4.2.5 on 2023-09-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_brand_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
